import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootClientWrapper from "./providers/RootClientWrapper";
import { Archivo } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap", // biar cepat tampil
});

export const metadata = {
  title: "Test Sellerpintar Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased bg-gray-100`}>
        <RootClientWrapper>{children}</RootClientWrapper>
      </body>
    </html>
  );
}
